accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUp.as_view(),name='signup'),

]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(),name='all'),
    path('new/', views.CreatePost.as_view(),name='create'),
    path('by/<slug:username>/',views.UserPosts.as_view(),name='for_user'),
    path('by/<slug:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),

]

socialforum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/',include('posts.urls', namespace='posts')),
    path('groups/',include('groups.urls', namespace='groups')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Star Social</title>
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Font Awesome (Icons) -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.1/css/all.css" integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q" crossorigin="anonymous">


    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">


    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'socialforum/css/master.css' %}">
</head>
<body>
    <nav class='mynav navbar navbar-expand-sm' role='navigation' id='navbar'>
        <div class='container'>
            <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
            <ul class='navbar-nav navbar-right'>
                
                {% if user.is_authenticated %}
                    <li class='nav-item'><a class='nav-link' href="{% url 'posts:create' %}">Post</a></li>
                    <li class='nav-item'><a class='nav-link' href="{% url 'groups:all' %}">Groups</a></li>
                    <li class='nav-item'><a class='nav-link' href="{% url 'groups:create' %}">Create Group</a></li>
                    <li class='nav-item'><a class='nav-link' href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li class='nav-item'></li><a class='nav-link' href="{% url 'groups:all' %}">Groups</a></li>
                    <li class='nav-item'><a class='nav-link' href="{% url 'accounts:login' %}">Log In</a></li>
                    <li class='nav-item'><a class='nav-link' href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
                    
            </ul>
        </div>
    </nav>
    
    <div class='container mycontent'>
            {% block content %}
        
            {% endblock content %}
    </div>
    <canvas id="canvas"></canvas>
</body>

<script type='text/javascript' src="{% static 'socialforum/js/master.js' %}">
</script>
</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}
    <h1>Welcome to Star Social!</h1>
{% endblock content %}
    

templates/test.html
{% extends 'base.html' %}


{% block content %}
    <h1>You are now logged in!</h1>
{% endblock content %}
    

templates/thanks.html
{% extends 'base.html' %}


{% block content %}
    <h1>Thanks for visiting, come back soon!</h1>
{% endblock content %}
    